INSERT INTO facility_table(province, district, facility_name) VALUES
('Central','Chibombo','Chamakubi'),
('Central','Chibombo','Chikobo'),
('Central','Chibombo','Chikonkomene'),
('Central','Itezhi-Tezhi','Banamwaze'),
('Central','Itezhi-Tezhi','Basanga'),
('Central','Itezhi-Tezhi','Basanga'),
('Central','Kabwe','Bwacha'),
('Central','Kabwe','Chindwini Camp'),
('Central','Kabwe','Kabwe Mine. Hosp.'),
('Central','Kabwe','Kabwe General Hospital'),
('Central','Kabwe','Kangomba'),
('Central','Kabwe','Mahatma Gandhi Memorial'),
('Central','Kapiri Mposhi','Chankomo'),
('Central','Kapiri Mposhi','Chapusha'),
('Central','Kapiri Mposhi','Kapiri Mposhi Hospital'),
('Central','Kapiri Mposhi','Kawama'),
('Central','Kapiri Mposhi','Luanshimba'),
('Copperbelt','Chililabombwe','Konkola Mine Hospital'),
('Copperbelt','Chililabombwe','Chimfunshi'),
('Copperbelt','Chililabombwe','Kakoso'),
('Copperbelt','Chililabombwe','Kasumbalesa'),
('Copperbelt','Chingola','Chawama'),
('Copperbelt','Chingola','Chiwempala'),
('Copperbelt','Chingola','Health centre 1'),
('Copperbelt','Kalulushi','Chambishi GRZ Clinic'),
('Copperbelt','Kalulushi','Health centre 1'),
('Copperbelt','Kalulushi','Chambishi Mine Clinic'),
('Copperbelt','Kalulushi','Kalulushi GRZ'),
('Copperbelt','Kalulushi','Chibuluma HC'),
('Copperbelt','Kitwe','Buchi Main'),
('Copperbelt','Kitwe','Buchi Small'),
('Copperbelt','Kitwe','Bulangililo'),
('Copperbelt','Kitwe','CBU'),
('Copperbelt','Kitwe','Chamboli J'),
('Copperbelt','Luanshya','73 Independence'),
('Copperbelt','Luanshya','Allessandras'),
('Copperbelt','Luanshya','Baluba'),
('Copperbelt','Luanshya','Chaisa (section 9)'),
('Copperbelt','Luanshya','Kafubu Block'),
('Copperbelt','Luanshya','Luanshya District Hospital'),
('Copperbelt','Luanshya','Luanshya Main'),
('Copperbelt','Luanshya','Mikomfwa Clinic'),
('Copperbelt','Luanshya','Mpatamatu Section 26'),
('Copperbelt','Luanshya','Roan Antelope Hospital'),
('Copperbelt','Lufwanyama','Bulaya'),
('Copperbelt','Lufwanyama','Chantente'),
('Copperbelt','Lufwanyama','Chikabuke'),
('Copperbelt','Lufwanyama','Chinemu'),
('Copperbelt','Lufwanyama','Fungulwe'),
('Copperbelt','Lufwanyama','Kansoka'),
('Copperbelt','Masaiti','Bangwe'),
('Copperbelt','Masaiti','ChikumbiChilese'),
('Copperbelt','Masaiti','Chinondo'),
('Copperbelt','Masaiti','Chondwe'),
('Copperbelt','Masaiti','Chiwala'),
('Copperbelt','Masaiti','Fiwale'),
('Eastern','Chadiza','Bwanunkha'),
('Eastern','Chadiza','Chadiza'),
('Eastern','Chadiza','Chanida'),
('Eastern','Chadiza','Chanjowe'),
('Eastern','Chadiza','Chikoma'),
('Eastern','Chadiza','Madzaela'),
('Eastern','Chadiza','Mchenjeza'),
('Eastern','Chipata','Champhande'),
('Eastern','Chipata','Chikando'),
('Eastern','Chipata','Chinyaku'),
('Eastern','Chipata','Chipata General Hosp.'),
('Eastern','Chipata','Eastern Command'),
('Eastern','Chipata','Jerusalem'),
('Eastern','Chipata','Kapata Urban'),
('Eastern','Chipata','Kasenengwa'),
('Eastern','Chipata','Lunkwakwa'),
('Eastern','Chipata','Mwami Hospital'),
('Eastern','Katete','Chibolya'),
('Eastern','Katete','Chilasa'),
('Eastern','Katete','Chimtende'),
('Eastern','Katete','Chimtengo'),
('Eastern','Katete','Chimunsi'),
('Eastern','Lundazi','Chasefu'),
('Eastern','Lundazi','Chitungulu'),
('Eastern','Lundazi','Kanyanga'),
('Eastern','Lundazi','Kazembe'),
('Eastern','Lundazi','Lundazi District Hospital'),
('Eastern','Lundazi','Lundazi UHC'),
('Eastern','Lundazi','Malandula'),
('Eastern','Mambwe','Kamoto Mission Hospital'),
('Eastern','Mambwe','Kakumbi'),
('Eastern','Mambwe','St Lukes Msoro'),
('Eastern','Mambwe','Masumba'),
('Eastern','Mambwe','Kasamanda'),
('Eastern','Mambwe','Kamoto HAHC'),
('Lusaka','Chilanga','Chilanga'),
('Lusaka','Chilanga','Kazimva'),
('Lusaka','Chilanga','Kris Katumba'),
('Lusaka','Chilanga','Mt Makulu'),
('Lusaka','Chilanga','Mwembeshi'),
('Lusaka','Chilanga','Mwembeshi Prisons'),
('Lusaka','Chilanga','Mwembeshi Prisons'),
('Lusaka','Chongwe','Chainda'),
('Lusaka','Chongwe','Chalimbana'),
('Lusaka','Chongwe','Chikumbi'),
('Lusaka','Chongwe','Chongwe'),
('Lusaka','Chongwe','Ellensdale'),
('Lusaka','Kafue','Chanyanya'),
('Lusaka','Kafue','Chiawa'),
('Lusaka','Kafue','Chikupi'),
('Lusaka','Kafue','Kafue District Hospital'),
('Lusaka','Kafue','Railway GRZ MoH'),
('Lusaka','Luangwa','Chitope RHC'),
('Lusaka','Luangwa','Kasinsa RHC'),
('Lusaka','Luangwa','Katondwe Mission Hospital'),
('Lusaka','Luangwa','Kavalamanja RHC'),
('Lusaka','Luangwa','Luangwa Boma'),
('Lusaka','Luangwa','Sinyawagora'),
('Lusaka','Lusaka','A & T Dental Surgery'),
('Lusaka','Lusaka','Baba Medical Centre'),
('Lusaka','Lusaka','Beit Cure'),
('Lusaka','Lusaka','Blessings Medical'),
('Lusaka','Lusaka','Cancer Disease Hosp.'),
('Lusaka','Lusaka','Chainama Hills Hospital'),
('Lusaka','Lusaka','Matero Main'),
('Lusaka','Lusaka','Matero Reference'),
('Lusaka','Rufunsa','Bundabunda'),
('Lusaka','Rufunsa','Chimusanya'),
('Lusaka','Rufunsa','Chinyunyu'),
('Lusaka','Rufunsa','Chitemalesa'),
('Lusaka','Rufunsa','Chiyota'),
('Lusaka','Rufunsa','HAHC Mpanshya'),
('Lusaka','Rufunsa','Nyangwena'),
('Lusaka','Rufunsa','Rufunsa'),
('Luapula','Chembe','Chembe'),
('Luapula','Chembe','Chipete'),
('Luapula','Chembe','Kundamfumu'),
('Luapula','Chembe','Kasomalwela'),
('Luapula','Chembe','Lukola'),
('Luapula','Chienge','Chipungu'),
('Luapula','Chienge','Kabole'),
('Luapula','Chienge','Kabwe'),
('Luapula','Chienge','Kalembwe'),
('Luapula','Chienge','Lambwe Chomba'),
('Luapula','Chienge','Luchinda*'),
('Luapula','Chienge','Mukunta'),
('Luapula','Chienge','Mwabu'),
('Luapula','Chipili','Chipili'),
('Luapula','Chipili','Kaoma Makasa'),
('Luapula','Chipili','Mwenda'),
('Luapula','Chipili','Mutipula'),
('Luapula','Chipili','Musalango'),
('Luapula','Chipili','Mupeta'),
('Luapula','Chipili','Lupososhi');
